In [226]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [229]:
path = "onlinefoods.csv"
df_noid = pd.read_csv(path)

In [230]:
# menampilkan 10 baris awal dari dataset 
df_noid.head(10)

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
0,20,Female,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,12.9770,77.5773,560009,Yes,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,12.9551,77.6593,560017,Yes,Negative,Yes
3,22,Female,Single,Student,No Income,Graduate,6,12.9473,77.5616,560019,Yes,Positive,Yes
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,12.9850,77.5533,560010,Yes,Positive,Yes
5,27,Female,Married,Employee,More than 50000,Post Graduate,2,12.9299,77.6848,560103,Yes,Positive,Yes
6,22,Male,Single,Student,No Income,Graduate,3,12.9770,77.5773,560009,Yes,Positive,Yes
7,24,Female,Single,Student,No Income,Post Graduate,3,12.9828,77.6131,560042,Yes,Positive,Yes
8,23,Female,Single,Student,No Income,Post Graduate,2,12.9766,77.5993,560001,Yes,Positive,Yes
9,23,Female,Single,Student,No Income,Post Graduate,4,12.9854,77.7081,560048,Yes,Positive,Yes

In [231]:
# menampilkan 10 baris akhir dari dataset
df_noid.tail(10)

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
378,23,Female,Single,Employee,25001 to 50000,Post Graduate,2,12.9847,77.5491,560100,Yes,Positive,Yes
379,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,12.9850,77.5533,560010,Yes,Positive,Yes
380,27,Female,Married,Employee,More than 50000,Post Graduate,2,12.9299,77.6848,560103,Yes,Positive,Yes
381,22,Male,Single,Student,No Income,Graduate,3,12.9770,77.5773,560009,Yes,Positive,Yes
382,24,Female,Single,Student,No Income,Post Graduate,3,12.9828,77.6131,560042,Yes,Positive,Yes
383,23,Female,Single,Student,No Income,Post Graduate,2,12.9766,77.5993,560001,Yes,Positive,Yes
384,23,Female,Single,Student,No Income,Post Graduate,4,12.9854,77.7081,560048,Yes,Positive,Yes
385,22,Female,Single,Student,No Income,Post Graduate,5,12.9850,77.5533,560010,Yes,Positive,Yes
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,12.9770,77.5773,560009,Yes,Positive,Yes
387,23,Male,Single,Student,No Income,Post Graduate,5,12.8988,77.5764,560078,Yes,Positive,Yes

In [232]:
# mengungkap tipe-tipe data dari setiap kolom
print(df_noid.dtypes)

Age                             int64
Gender                         object
Marital Status                 object
Occupation                     object
Monthly Income                 object
Educational Qualifications     object
Family size                     int64
latitude                      float64
longitude                     float64
Pin code                        int64
Output                         object
Feedback                       object
Unnamed: 12                    object
dtype: object

In [233]:
df_noid.count()

Age                           388
Gender                        388
Marital Status                388
Occupation                    388
Monthly Income                388
Educational Qualifications    388
Family size                   388
latitude                      388
longitude                     388
Pin code                      388
Output                        388
Feedback                      388
Unnamed: 12                   388
dtype: int64

In [234]:
duplicate_rows_df = df_noid[df_noid.duplicated()]
print("number of duplicate rows: ", duplicate_rows_df.shape)

number of duplicate rows:  (103, 13)

In [235]:
#  mencari jumlah nilai-nilai yang hilang (NaN/null) dalam setiap kolom dataframe
print(df_noid.isnull().sum())

Age                           0
Gender                        0
Marital Status                0
Occupation                    0
Monthly Income                0
Educational Qualifications    0
Family size                   0
latitude                      0
longitude                     0
Pin code                      0
Output                        0
Feedback                      0
Unnamed: 12                   0
dtype: int64

In [236]:
df = df_noid.dropna() # menghapus nilai yang hilang
df.count()

Age                           388
Gender                        388
Marital Status                388
Occupation                    388
Monthly Income                388
Educational Qualifications    388
Family size                   388
latitude                      388
longitude                     388
Pin code                      388
Output                        388
Feedback                      388
Unnamed: 12                   388
dtype: int64

In [237]:
df_noid = df.iloc[:,2:]
df_noid

,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
0,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive,Yes
1,Single,Student,Below Rs.10000,Graduate,3,12.9770,77.5773,560009,Yes,Positive,Yes
2,Single,Student,Below Rs.10000,Post Graduate,3,12.9551,77.6593,560017,Yes,Negative,Yes
3,Single,Student,No Income,Graduate,6,12.9473,77.5616,560019,Yes,Positive,Yes
4,Single,Student,Below Rs.10000,Post Graduate,4,12.9850,77.5533,560010,Yes,Positive,Yes
...,...,...,...,...,...,...,...,...,...,...,...
383,Single,Student,No Income,Post Graduate,2,12.9766,77.5993,560001,Yes,Positive,Yes
384,Single,Student,No Income,Post Graduate,4,12.9854,77.7081,560048,Yes,Positive,Yes
385,Single,Student,No Income,Post Graduate,5,12.9850,77.5533,560010,Yes,Positive,Yes
386,Single,Student,Below Rs.10000,Post Graduate,2,12.9770,77.5773,560009,Yes,Positive,Yes
387,Single,Student,No Income,Post Graduate,5,12.8988,77.5764,560078,Yes,Positive,Yes

In [238]:
# jika ingin menampilkan juga statistik kolom- 
# yang bertipe non-numerik, mencakup beberapa banyak nilai unik- 
# dalam kolom (unique), nilai modus(top), serta frekuensi modus(freq)
df_noid.describe(include="all")

,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
count,388,388,388,388,388.000000,388.000000,388.000000,388.000000,388,388,388
unique,3,4,5,5,NaN,NaN,NaN,NaN,2,2,2
top,Single,Student,No Income,Graduate,NaN,NaN,NaN,NaN,Yes,Positive,Yes
freq,268,207,187,177,NaN,NaN,NaN,NaN,301,317,301
mean,NaN,NaN,NaN,NaN,3.280928,12.972058,77.600160,560040.113402,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,1.351025,0.044489,0.051354,31.399609,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,1.000000,12.865200,77.484200,560001.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,2.000000,12.936900,77.565275,560010.750000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,3.000000,12.977000,77.592100,560033.500000,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,4.000000,12.997025,77.630900,560068.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,6.000000,13.102000,77.758200,560109.000000,NaN,NaN,NaN

In [239]:
# menampilkan statistik dasar setiap kolom data yang bertipe numerik.
df_noid.describe()

       Family size    latitude   longitude       Pin code
count   388.000000  388.000000  388.000000     388.000000
mean      3.280928   12.972058   77.600160  560040.113402
std       1.351025    0.044489    0.051354      31.399609
min       1.000000   12.865200   77.484200  560001.000000
25%       2.000000   12.936900   77.565275  560010.750000
50%       3.000000   12.977000   77.592100  560033.500000
75%       4.000000   12.997025   77.630900  560068.000000
max       6.000000   13.102000   77.758200  560109.000000

In [240]:
kolom_numerik = df.select_dtypes(include=['number'])

In [241]:
mean = kolom_numerik.mean()
print(mean)

Age                24.628866
Family size         3.280928
latitude           12.972058
longitude          77.600160
Pin code       560040.113402
dtype: float64

In [242]:
median = kolom_numerik.median()
print(median)

Age                24.0000
Family size         3.0000
latitude           12.9770
longitude          77.5921
Pin code       560033.5000
dtype: float64

In [243]:
varians = kolom_numerik.var()
print(varians)

Age              8.854152
Family size      1.825268
latitude         0.001979
longitude        0.002637
Pin code       985.935427
dtype: float64

In [244]:
# menghitung standar deviasi dari setiap kolom 
deviasi = kolom_numerik.std()
print(deviasi)

Age             2.975593
Family size     1.351025
latitude        0.044489
longitude       0.051354
Pin code       31.399609
dtype: float64

In [245]:
# menghitung kuantil ke-75 dari setiap kolom
kuantil = kolom_numerik.quantile(0.75)
print(kuantil)

Age                26.000000
Family size         4.000000
latitude           12.997025
longitude          77.630900
Pin code       560068.000000
Name: 0.75, dtype: float64

In [246]:
# membulatkan setiap elemen dalam dataframe df_noid
df_noid.round(2).mode()

,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
0,Single,Student,No Income,Graduate,3,12.98,77.58,560009,Yes,Positive,Yes

In [255]:
q1 = kolom_numerik.quantile(0.25)
q3 = kolom_numerik.quantile(0.75)
iqr = q3 - q1
print(iqr)

Age             3.000000
Family size     2.000000
latitude        0.060125
longitude       0.065625
Pin code       57.250000
dtype: float64

In [259]:
# handle warning 
import warnings 
warnings.filterwarnings('ignore')

# outlier filter
df_noid_align, iqr_new = kolom_numerik.align(iqr, axis=1, copy=False, join='outer')
outlier_filter = (kolom_numerik < q1 - 1.5 * iqr_new) | (kolom_numerik > q3 + 1.5 * iqr_new)
outlier_filter

       Age  Family size  latitude  longitude  Pin code
0    False        False     False      False     False
1    False        False     False      False     False
2    False        False     False      False     False
3    False        False     False      False     False
4    False        False     False      False     False
..     ...          ...       ...        ...       ...
383  False        False     False      False     False
384  False        False     False      False     False
385  False        False     False      False     False
386  False        False     False      False     False
387  False        False     False      False     False

[388 rows x 5 columns]

In [260]:
df.count()

Age                           388
Gender                        388
Marital Status                388
Occupation                    388
Monthly Income                388
Educational Qualifications    388
Family size                   388
latitude                      388
longitude                     388
Pin code                      388
Output                        388
Feedback                      388
Unnamed: 12                   388
dtype: int64