In [285]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [286]:
path = "laptops.csv"
df = pd.read_csv(path)

In [287]:
# menampilkan 10 baris awal dari dataset 
df.head(10)

,index,brand,Model,Price,Rating,processor_brand,processor_tier,num_cores,num_threads,ram_memory,...,secondary_storage_type,secondary_storage_capacity,gpu_brand,gpu_type,is_touch_screen,display_size,resolution_width,resolution_height,OS,year_of_warranty
0,1,tecno,Tecno Megabook T1 Laptop (11th Gen Core i3/ 8G...,23990,63,intel,core i3,2,4,8,...,No secondary storage,0,intel,integrated,False,15.6,1920,1080,windows,1
1,2,tecno,Tecno Megabook T1 Laptop (11th Gen Core i7/ 16...,35990,67,intel,core i7,4,8,16,...,No secondary storage,0,intel,integrated,False,15.6,1920,1080,windows,1
2,3,hp,HP Victus 15-fb0157AX Gaming Laptop (AMD Ryzen...,51100,73,amd,ryzen 5,6,12,8,...,No secondary storage,0,amd,dedicated,False,15.6,1920,1080,windows,1
3,4,acer,Acer Extensa EX214-53 Laptop (12th Gen Core i5...,39990,62,intel,core i5,12,16,8,...,No secondary storage,0,intel,integrated,False,14.0,1920,1080,windows,1
4,5,lenovo,Lenovo V15 82KDA01BIH Laptop (AMD Ryzen 3 5300...,28580,62,amd,ryzen 3,4,8,8,...,No secondary storage,0,amd,integrated,False,15.6,1920,1080,windows,1
5,6,apple,Apple MacBook Air 2020 MGND3HN Laptop (Apple M...,70990,45,apple,m1,8,8,8,...,No secondary storage,0,apple,apple,False,13.3,2560,1600,mac,1
6,7,infinix,Infinix INBook Y2 Plus Laptop (11th Gen Core i...,34990,56,intel,core i5,4,8,16,...,No secondary storage,0,intel,integrated,False,15.6,1920,1080,windows,1
7,8,asus,Asus TUF Gaming F15 FX506HF-HN024W Gaming Lapt...,49990,70,intel,core i5,6,12,8,...,No secondary storage,0,nvidia,dedicated,False,15.6,1920,1080,windows,1
8,9,hp,HP 15s-fq5007TU Laptop (12th Gen Core i3/ 8GB/...,36990,60,intel,core i3,6,8,8,...,No secondary storage,0,intel,integrated,False,15.6,1920,1080,windows,1
9,10,infinix,Infinix Zerobook 2023 Laptop (13th Gen Core i9...,59990,71,intel,core i9,14,20,32,...,No secondary storage,0,intel,integrated,False,15.6,1920,1080,windows,1

In [288]:
# menampilkan 10 baris akhir dari dataset
df.tail(10)

,index,brand,Model,Price,Rating,processor_brand,processor_tier,num_cores,num_threads,ram_memory,...,secondary_storage_type,secondary_storage_capacity,gpu_brand,gpu_type,is_touch_screen,display_size,resolution_width,resolution_height,OS,year_of_warranty
981,993,msi,MSI Katana 15 B13VFK-296IN Gaming Laptop (13th...,119990,76,intel,core i7,10,16,16,...,No secondary storage,0,nvidia,dedicated,False,15.6,1920,1080,windows,2
982,994,asus,Asus Zenbook 14 OLED 2023 UM3402YA-KM551WS Lap...,77990,68,amd,ryzen 5,6,12,16,...,No secondary storage,0,amd,integrated,False,14.0,2880,1800,windows,1
983,995,asus,Asus Vivobook 16 2023 M1605YA-MB551WS Laptop (...,66990,65,amd,ryzen 5,6,12,16,...,No secondary storage,0,amd,integrated,False,16.0,1920,1200,windows,1
984,996,asus,Asus Vivobook 16 2023 M1605YA-MB541WS Laptop (...,59990,64,amd,ryzen 5,6,12,16,...,No secondary storage,0,amd,integrated,False,16.0,1920,1200,windows,1
985,997,acer,Acer Nitro 5 AN515-47 NH.QL3SI.003 Gaming Lapt...,75500,67,amd,ryzen 7,8,16,8,...,No secondary storage,0,nvidia,dedicated,False,15.6,1920,1080,windows,1
986,998,asus,Asus Vivobook Pro 15 M6500QC-HN542WS Laptop (R...,65990,68,amd,ryzen 5,6,12,16,...,No secondary storage,0,nvidia,dedicated,False,15.6,1920,1080,windows,1
987,999,msi,MSI Thin GF63 12VE-070IN Gaming Laptop (12th G...,91990,73,intel,core i7,10,16,16,...,No secondary storage,0,nvidia,dedicated,False,15.6,1920,1080,windows,2
988,1000,asus,Asus Vivobook Go 15 2023 E1504FA-NJ522WS Lapto...,44990,59,amd,ryzen 5,4,8,8,...,No secondary storage,0,amd,integrated,False,15.6,1920,1080,windows,1
989,1001,asus,Asus Zenbook 14 2023 UM3402YA-KP541WS Laptop (...,67990,68,amd,ryzen 5,6,12,16,...,No secondary storage,0,amd,integrated,False,14.0,2560,1600,windows,1
990,1002,hp,HP Chromebook 15a-na0008TU Laptop (Intel Celer...,20990,37,intel,celeron,2,2,4,...,No secondary storage,0,intel,integrated,False,15.6,1366,768,chrome,1

In [289]:
# mengungkap tipe-tipe data dari setiap kolom
print(df.dtypes)

index                           int64
brand                          object
Model                          object
Price                           int64
Rating                          int64
processor_brand                object
processor_tier                 object
num_cores                       int64
num_threads                     int64
ram_memory                      int64
primary_storage_type           object
primary_storage_capacity        int64
secondary_storage_type         object
secondary_storage_capacity      int64
gpu_brand                      object
gpu_type                       object
is_touch_screen                  bool
display_size                  float64
resolution_width                int64
resolution_height               int64
OS                             object
year_of_warranty               object
dtype: object

In [290]:
df.count()

index                         991
brand                         991
Model                         991
Price                         991
Rating                        991
processor_brand               991
processor_tier                991
num_cores                     991
num_threads                   991
ram_memory                    991
primary_storage_type          991
primary_storage_capacity      991
secondary_storage_type        991
secondary_storage_capacity    991
gpu_brand                     991
gpu_type                      991
is_touch_screen               991
display_size                  991
resolution_width              991
resolution_height             991
OS                            991
year_of_warranty              991
dtype: int64

In [291]:
duplicate_rows_df = df[df.duplicated()]
print("number of duplicate rows: ", duplicate_rows_df.shape)

number of duplicate rows:  (0, 22)

In [292]:
#  mencari jumlah nilai-nilai yang hilang (NaN/null) dalam setiap kolom dataframe
print(df.isnull().sum())

index                         0
brand                         0
Model                         0
Price                         0
Rating                        0
processor_brand               0
processor_tier                0
num_cores                     0
num_threads                   0
ram_memory                    0
primary_storage_type          0
primary_storage_capacity      0
secondary_storage_type        0
secondary_storage_capacity    0
gpu_brand                     0
gpu_type                      0
is_touch_screen               0
display_size                  0
resolution_width              0
resolution_height             0
OS                            0
year_of_warranty              0
dtype: int64

In [293]:
df = df.dropna() # menghapus nilai yang hilang
df.count()

index                         991
brand                         991
Model                         991
Price                         991
Rating                        991
processor_brand               991
processor_tier                991
num_cores                     991
num_threads                   991
ram_memory                    991
primary_storage_type          991
primary_storage_capacity      991
secondary_storage_type        991
secondary_storage_capacity    991
gpu_brand                     991
gpu_type                      991
is_touch_screen               991
display_size                  991
resolution_width              991
resolution_height             991
OS                            991
year_of_warranty              991
dtype: int64

In [294]:
df = df.iloc[:,2:]
df

,Model,Price,Rating,processor_brand,processor_tier,num_cores,num_threads,ram_memory,primary_storage_type,primary_storage_capacity,secondary_storage_type,secondary_storage_capacity,gpu_brand,gpu_type,is_touch_screen,display_size,resolution_width,resolution_height,OS,year_of_warranty
0,Tecno Megabook T1 Laptop (11th Gen Core i3/ 8G...,23990,63,intel,core i3,2,4,8,SSD,512,No secondary storage,0,intel,integrated,False,15.6,1920,1080,windows,1
1,Tecno Megabook T1 Laptop (11th Gen Core i7/ 16...,35990,67,intel,core i7,4,8,16,SSD,1024,No secondary storage,0,intel,integrated,False,15.6,1920,1080,windows,1
2,HP Victus 15-fb0157AX Gaming Laptop (AMD Ryzen...,51100,73,amd,ryzen 5,6,12,8,SSD,512,No secondary storage,0,amd,dedicated,False,15.6,1920,1080,windows,1
3,Acer Extensa EX214-53 Laptop (12th Gen Core i5...,39990,62,intel,core i5,12,16,8,SSD,512,No secondary storage,0,intel,integrated,False,14.0,1920,1080,windows,1
4,Lenovo V15 82KDA01BIH Laptop (AMD Ryzen 3 5300...,28580,62,amd,ryzen 3,4,8,8,SSD,512,No secondary storage,0,amd,integrated,False,15.6,1920,1080,windows,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986,Asus Vivobook Pro 15 M6500QC-HN542WS Laptop (R...,65990,68,amd,ryzen 5,6,12,16,SSD,512,No secondary storage,0,nvidia,dedicated,False,15.6,1920,1080,windows,1
987,MSI Thin GF63 12VE-070IN Gaming Laptop (12th G...,91990,73,intel,core i7,10,16,16,SSD,512,No secondary storage,0,nvidia,dedicated,False,15.6,1920,1080,windows,2
988,Asus Vivobook Go 15 2023 E1504FA-NJ522WS Lapto...,44990,59,amd,ryzen 5,4,8,8,SSD,512,No secondary storage,0,amd,integrated,False,15.6,1920,1080,windows,1
989,Asus Zenbook 14 2023 UM3402YA-KP541WS Laptop (...,67990,68,amd,ryzen 5,6,12,16,SSD,512,No secondary storage,0,amd,integrated,False,14.0,2560,1600,windows,1
990,HP Chromebook 15a-na0008TU Laptop (Intel Celer...,20990,37,intel,celeron,2,2,4,HDD,128,No secondary storage,0,intel,integrated,False,15.6,1366,768,chrome,1

In [295]:
# menampilkan statistik dasar setiap kolom data yang bertipe numerik.
df_noid.describe()

,Price,Rating,num_cores,num_threads,ram_memory,primary_storage_capacity,secondary_storage_capacity,display_size,resolution_width,resolution_height
count,991.000000,991.000000,991.000000,991.000000,991.000000,991.000000,991.000000,991.000000,991.000000,991.000000
mean,77266.504541,63.931382,8.128153,12.191726,13.047427,610.938446,4.004036,15.171241,2003.503532,1181.227043
std,57384.910269,10.190575,4.215499,5.585115,5.591188,266.927666,33.553936,0.938089,361.965292,263.884019
min,9800.000000,24.000000,2.000000,0.000000,2.000000,32.000000,0.000000,10.100000,1080.000000,768.000000
25%,43595.000000,58.000000,6.000000,8.000000,8.000000,512.000000,0.000000,14.000000,1920.000000,1080.000000
50%,61900.000000,64.000000,8.000000,12.000000,16.000000,512.000000,0.000000,15.600000,1920.000000,1080.000000
75%,89245.000000,71.000000,10.000000,16.000000,16.000000,512.000000,0.000000,15.600000,1920.000000,1200.000000
max,454490.000000,89.000000,24.000000,32.000000,36.000000,2048.000000,512.000000,18.000000,3840.000000,2560.000000

In [296]:
# jika ingin menampilkan juga statistik kolom- 
# yang bertipe non-numerik, mencakup beberapa banyak nilai unik- 
# dalam kolom (unique), nilai modus(top), serta frekuensi modus(freq)
df_noid.describe(include="all")

,Model,Price,Rating,processor_brand,processor_tier,num_cores,num_threads,ram_memory,primary_storage_type,primary_storage_capacity,secondary_storage_type,secondary_storage_capacity,gpu_brand,gpu_type,is_touch_screen,display_size,resolution_width,resolution_height,OS,year_of_warranty
count,991,991.000000,991.000000,991,991,991.000000,991.000000,991.000000,991,991.000000,991,991.000000,991,991,991,991.000000,991.000000,991.000000,991,991
unique,991,NaN,NaN,4,15,NaN,NaN,NaN,2,NaN,2,NaN,5,3,2,NaN,NaN,NaN,7,4
top,Tecno Megabook T1 Laptop (11th Gen Core i3/ 8G...,NaN,NaN,intel,core i5,NaN,NaN,NaN,SSD,NaN,No secondary storage,NaN,intel,integrated,False,NaN,NaN,NaN,windows,1
freq,1,NaN,NaN,705,335,NaN,NaN,NaN,964,NaN,976,NaN,462,616,903,NaN,NaN,NaN,924,900
mean,NaN,77266.504541,63.931382,NaN,NaN,8.128153,12.191726,13.047427,NaN,610.938446,NaN,4.004036,NaN,NaN,NaN,15.171241,2003.503532,1181.227043,NaN,NaN
std,NaN,57384.910269,10.190575,NaN,NaN,4.215499,5.585115,5.591188,NaN,266.927666,NaN,33.553936,NaN,NaN,NaN,0.938089,361.965292,263.884019,NaN,NaN
min,NaN,9800.000000,24.000000,NaN,NaN,2.000000,0.000000,2.000000,NaN,32.000000,NaN,0.000000,NaN,NaN,NaN,10.100000,1080.000000,768.000000,NaN,NaN
25%,NaN,43595.000000,58.000000,NaN,NaN,6.000000,8.000000,8.000000,NaN,512.000000,NaN,0.000000,NaN,NaN,NaN,14.000000,1920.000000,1080.000000,NaN,NaN
50%,NaN,61900.000000,64.000000,NaN,NaN,8.000000,12.000000,16.000000,NaN,512.000000,NaN,0.000000,NaN,NaN,NaN,15.600000,1920.000000,1080.000000,NaN,NaN
75%,NaN,89245.000000,71.000000,NaN,NaN,10.000000,16.000000,16.000000,NaN,512.000000,NaN,0.000000,NaN,NaN,NaN,15.600000,1920.000000,1200.000000,NaN,NaN
max,NaN,454490.000000,89.000000,NaN,NaN,24.000000,32.000000,36.000000,NaN,2048.000000,NaN,512.000000,NaN,NaN,NaN,18.000000,3840.000000,2560.000000,NaN,NaN

In [297]:
kolom_numerik = df.select_dtypes(include='number')

In [298]:
mean = kolom_numerik.mean()
print(mean)

Price                         77266.504541
Rating                           63.931382
num_cores                         8.128153
num_threads                      12.191726
ram_memory                       13.047427
primary_storage_capacity        610.938446
secondary_storage_capacity        4.004036
display_size                     15.171241
resolution_width               2003.503532
resolution_height              1181.227043
dtype: float64

In [299]:
sum = kolom_numerik.sum()
print(sum)

Price                         76571106.0
Rating                           63356.0
num_cores                         8055.0
num_threads                      12082.0
ram_memory                       12930.0
primary_storage_capacity        605440.0
secondary_storage_capacity        3968.0
display_size                     15034.7
resolution_width               1985472.0
resolution_height              1170596.0
dtype: float64

In [300]:
median = kolom_numerik.median()
print(median)

Price                         61900.0
Rating                           64.0
num_cores                         8.0
num_threads                      12.0
ram_memory                       16.0
primary_storage_capacity        512.0
secondary_storage_capacity        0.0
display_size                     15.6
resolution_width               1920.0
resolution_height              1080.0
dtype: float64

In [301]:
varians = kolom_numerik.var()
print(varians)

Price                         3.293028e+09
Rating                        1.038478e+02
num_cores                     1.777043e+01
num_threads                   3.119351e+01
ram_memory                    3.126138e+01
primary_storage_capacity      7.125038e+04
secondary_storage_capacity    1.125867e+03
display_size                  8.800105e-01
resolution_width              1.310189e+05
resolution_height             6.963478e+04
dtype: float64

In [302]:
# menghitung standar deviasi dari setiap kolom 
deviasi = kolom_numerik.std()
print(deviasi)

Price                         57384.910269
Rating                           10.190575
num_cores                         4.215499
num_threads                       5.585115
ram_memory                        5.591188
primary_storage_capacity        266.927666
secondary_storage_capacity       33.553936
display_size                      0.938089
resolution_width                361.965292
resolution_height               263.884019
dtype: float64

In [303]:
# menghitung kuantil ke-75 dari setiap kolom
kuantil = kolom_numerik.quantile(0.75)
print(kuantil)

Price                         89245.0
Rating                           71.0
num_cores                        10.0
num_threads                      16.0
ram_memory                       16.0
primary_storage_capacity        512.0
secondary_storage_capacity        0.0
display_size                     15.6
resolution_width               1920.0
resolution_height              1200.0
Name: 0.75, dtype: float64

In [304]:
# membulatkan setiap elemen dalam dataframe df_noid
df_noid.round(2).mode()

,Model,Price,Rating,processor_brand,processor_tier,num_cores,num_threads,ram_memory,primary_storage_type,primary_storage_capacity,secondary_storage_type,secondary_storage_capacity,gpu_brand,gpu_type,is_touch_screen,display_size,resolution_width,resolution_height,OS,year_of_warranty
0,ASUS TUF Gaming A16 Advantage Edition FA617XS-...,34990.0,58.0,intel,core i5,6.0,12.0,16.0,SSD,512.0,No secondary storage,0.0,intel,integrated,False,15.6,1920.0,1080.0,windows,1
1,AXL Vayu Book LAP01 Laptop (Celeron N4020/ 4GB...,39990.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AXL Vayu Book LAP02 Laptop (Celeron N4020/ 4GB...,46990.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Acer 16 Predator Neo NH.QLTSI.001 Laptop (13th...,49990.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Acer Aspire 3 14 A314-36M Laptop (Intel Core i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986,Zebronics Pro Series Z ZEB-NBC 4S 2023 Laptop ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
987,Zebronics ZEB-NBC 2S 2023 Laptop (11th Gen Cor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
988,Zebronics ZEB-NBC 5S 2023 Laptop (12th Gen Cor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
989,Zebronics ZEB-NBC 5S Laptop (12th Gen Core i7 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
990,iBall Excelance CompBook Laptop (AQC/ 2GB/ 32G...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [305]:
q1 = kolom_numerik.quantile(0.25)
q3 = kolom_numerik.quantile(0.75)
iqr = q3 - q1
print(iqr)

Price                         45650.0
Rating                           13.0
num_cores                         4.0
num_threads                       8.0
ram_memory                        8.0
primary_storage_capacity          0.0
secondary_storage_capacity        0.0
display_size                      1.6
resolution_width                  0.0
resolution_height               120.0
dtype: float64

In [306]:
# handle warning 
import warnings 
warnings.filterwarnings('ignore')

# outlier filter
df_noid_align, iqr_new = kolom_numerik.align(iqr, axis=1, copy=False, join='outer')
outlier_filter = (kolom_numerik < q1 - 1.5 * iqr_new) | (kolom_numerik > q3 + 1.5 * iqr_new)
outlier_filter

,Price,Rating,num_cores,num_threads,ram_memory,primary_storage_capacity,secondary_storage_capacity,display_size,resolution_width,resolution_height
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
986,False,False,False,False,False,False,False,False,False,False
987,False,False,False,False,False,False,False,False,False,False
988,False,False,False,False,False,False,False,False,False,False
989,False,False,False,False,False,False,False,False,True,True
990,False,True,False,False,False,True,False,False,True,True

In [307]:
df_noid[outlier_filter['Rating']] \
    .loc[:, ['Model', 'Rating']] \
    .sort_values(by=['Rating'], ascending=False)

                                                 Model  Rating
634  Lenovo IdeaPad 1 82V6005CIN Laptop (Celeron N4...      38
365  Acer Chromebook CB314-3H NX.K04SI.008 Laptop (...      38
728  AXL Vayu Book LAP02 Laptop (Celeron N4020/ 4GB...      38
389  Asus CX1101CMA-GJ0004 Chromebook (Celeron N402...      38
392  Asus Chromebook 14 CX1400CKA-EK0266 Laptop (Ce...      38
414  Acer Chromebook CB314-3H NX.K04SI.007 Laptop (...      38
636  HP Chromebook 15a-nb0002TU Laptop ( Intel Core...      38
486  Asus Chromebook CX1400CKA-EK0257 Laptop (Celer...      37
953  HP Chromebook 15a-na0012TU Laptop (Intel Celer...      37
730  AXL Vayu Book LAP01 Laptop (Celeron N4020/ 4GB...      37
640  Walker NU14A1 Laptop (Celeron N4020/ 4GB/ 128G...      37
990  HP Chromebook 15a-na0008TU Laptop (Intel Celer...      37
491  Asus Chromebook CX1500CKA-EJ0275 Laptop (Celer...      37
488  Asus Chromebook CX1400CKA-EK0335 Laptop (Celer...      37
325  Asus Chromebook CX1500CKA-EJ0247 Laptop (Celer...      37
169  Asus Chromebook CX1500CKA-EJ0241 Laptop (Celer...      35
372  Primebook PBMTWIFI11064 Wi-Fi Laptop (MediaTek...      31
70   Primebook 4G Android Laptop (MediaTek Kompanio...      26
192  Jio JioBook NB1112MM BLU 2023 Netbook Laptop (...      24

In [314]:
df_noid['processor_brand'].value_counts()

processor_brand
intel    705
amd      267
apple     15
other      4
Name: count, dtype: int64